server:
    port: ${PORT:8761} # Indicate the default PORT where this service will be started

eureka:
    client:
        registerWithEureka: false   #telling the server not to register himself in the service registry
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/

    server:
        waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync

